// Auth Tokens
export const FETCH_USER_AUTH_TOKEN = 'FETCH_USER_AUTH_TOKEN';
export const USER_AUTH_TOKEN_RECEIVED = 'USER_AUTH_TOKEN_RECEIVED';
export const USER_AUTH_TOKEN_DENIED = 'USER_AUTH_TOKEN_DENIED';