// Auth Tokens
export const FETCH_USER_AUTH_TOKEN = 'FETCH_USER_AUTH_TOKEN';
export const GET_USER_AUTH_TOKEN = 'GET_USER_AUTH_TOKEN';
export const REMOVE_USER_AUTH_TOKEN = 'REMOVE_USER_AUTH_TOKEN';

export const FETCH_USER_AUTH_TOKEN_SUCCEEDED = 'USER_AUTH_TOKEN_SUCCEEDED';
export const USER_AUTH_TOKEN_FAILED = 'USER_AUTH_TOKEN_FAILED';


// Socket
export const CREATE_SOCKET = 'CREATE_SOCKET';
export const SOCKET_CREATED = 'SOCKET_CREATED';
export const SOCKET_FAILED = 'SOCKET_FAILED';
export const SOCKET_SEND = 'SOCKET_SEND'
// 

